# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Internal Build to Play Store"
  lane :internal_release do
    upload_to_play_store(track: 'internal', aab: 'app/build/outputs/apk/production/release/app-production-release.aab')
  end

  desc "Submit a new Beta Build to Play Store"
  lane :beta_release do
    upload_to_play_store(track: 'beta', aab: 'app/build/outputs/apk/production/release/app-production-release.aab')
  end

  desc "Promote Beta to Production"
  lane :promote_beta_to_production do
    upload_to_play_store(track: 'beta', track_promote_to: 'production')
  end
end
