name: Android Build

on:
  pull_request:
    branches: [ develop, master ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Github 저장소를 로컬로 복사합니다.
      - uses: actions/checkout@v3

      # gradle 빌드을 위해 JDK를 세팅합니다.
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # 빌드에 필요한 환경변수를 세팅합니다.
      - name: Setting env
        run: |
          echo "BUILD_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "STORE_PASSWORD=${{ secrets.STORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      # gradlew에 실행 권한을 부여합니다.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # devRelease 버전의 apk를 빌드합니다.
      - name: Build with Gradle
        run: ./gradlew --no-daemon :app:storybook:assembleDevRelease