# PR이 정상적으로 빌드되는지 확인하기 위한 워크플로입니다.
name: Android Build

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Github 저장소를 로컬로 복사합니다.
      - uses: actions/checkout@v3

      # gradle 빌드을 위해 JDK를 세팅합니다.
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # gradlew에 실행 권한을 부여합니다.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # devDebug 버전의 apk를 빌드합니다.
      - name: Build with Gradle
        run: ./gradlew --no-daemon :app:storybook:assembleDevDebug